require 'ipfs-http-client/commands/base'
require 'ipfs-http-client/commands/ls'
require 'ipfs-http-client/commands/cat'
require 'ipfs-http-client/commands/cat_to_file'
require 'ipfs-http-client/commands/add'
require 'ipfs-http-client/commands/add_dir'
require 'ipfs-http-client/commands/pin_rm'
